import Bot_test as app
import payment_reuse_telegram  # noqa: F401
import legal_telegram  # noqa: F401
from financial_hardening import install_financial_hardening
from financial_display_hardening import install_telegram_financial_display_hardening
from student_stats_hardening import install_student_stats_hardening
from student_account_hardening import install_student_account_hardening
from tutor_students_hardening import install_telegram_tutor_students_hardening
from pricing_text_hardening import install_pricing_text_hardening
from help_text_hardening import install_help_text_hardening
from subscription_booking import install_telegram_subscription_booking
from subscription_purchase_hardening import install_telegram_subscription_purchase_hardening
from tutor_confirmation_hardening import install_telegram_tutor_confirmation
from telegram_email_hardening import install_telegram_email_hardening
from telegram_payment_hardening import install_telegram_payment_hardening
from subscription_cancel_hardening import install_subscription_cancel_release
from completed_cancellation_hardening import install_completed_cancellation_guard
from completion_hardening import install_telegram_completion_hardening
from payment_poll_hardening import install_telegram_payment_poll_hardening
from access_hardening import install_telegram_materials_guard
from input_hardening import install_telegram_input_hardening
from callback_hardening import install_telegram_callback_hardening
from support_hardening import install_telegram_support_hardening
from delivery_hardening import install_delivery_hardening
from contact_delivery_hardening import install_telegram_contact_delivery_hardening
from telegram_messaging_identity_hardening import install_telegram_messaging_identity_hardening
from pagination_hardening import install_telegram_pagination_hardening
from core_flow_hardening import install_telegram_core_flow_hardening
from manual_test_hardening import (
    install_records_runtime_hardening,
    install_telegram_manual_test_hardening,
)
from email_payment_safety_hardening import install_telegram_email_payment_safety
from runtime_hardening import install_telegram_hardening

install_financial_hardening(app)
install_telegram_financial_display_hardening(app)
install_student_stats_hardening(app)
install_student_account_hardening(app, "telegram")
install_telegram_tutor_students_hardening(app)
install_pricing_text_hardening(app)
install_help_text_hardening(app, "telegram")
install_telegram_subscription_booking(app)
install_telegram_subscription_purchase_hardening(app)
install_telegram_tutor_confirmation(app)
install_telegram_email_hardening(app)
install_telegram_payment_hardening(app)
install_subscription_cancel_release(app)
install_completed_cancellation_guard(app)
install_telegram_completion_hardening(app)
install_telegram_payment_poll_hardening(app)
install_telegram_materials_guard(app)
install_telegram_input_hardening(app)
install_telegram_callback_hardening(app)
install_telegram_support_hardening(app)
install_delivery_hardening(app)
install_telegram_contact_delivery_hardening(app)
install_telegram_messaging_identity_hardening(app)
install_telegram_pagination_hardening(app)
install_telegram_core_flow_hardening(app)
install_records_runtime_hardening(app)
install_telegram_manual_test_hardening(app)
install_telegram_email_payment_safety(app)
install_telegram_hardening(app)


async def main():
    return await app.main()


if __name__ == "__main__":
    app.legacy.logging.basicConfig(level=app.legacy.logging.INFO, stream=app.legacy.sys.stdout)
    app.legacy.asyncio.run(main())
