import Bot_test as app
import payment_reuse_telegram  # noqa: F401
import legal_telegram  # noqa: F401
from financial_hardening import install_financial_hardening
from student_stats_hardening import install_student_stats_hardening
from student_account_hardening import install_student_account_hardening
from pricing_text_hardening import install_pricing_text_hardening
from tutor_archive_hardening import install_tutor_archive_hardening
from subscription_booking import install_telegram_subscription_booking
from tutor_confirmation_hardening import install_telegram_tutor_confirmation
from telegram_email_hardening import install_telegram_email_hardening
from subscription_cancel_hardening import install_subscription_cancel_release
from completion_hardening import install_telegram_completion_hardening
from access_hardening import install_telegram_materials_guard
from input_hardening import install_telegram_input_hardening
from callback_hardening import install_telegram_callback_hardening
from delivery_hardening import install_delivery_hardening
from contact_delivery_hardening import install_telegram_contact_delivery_hardening
from pagination_hardening import install_telegram_pagination_hardening
from runtime_hardening import install_telegram_hardening

install_financial_hardening(app)
install_student_stats_hardening(app)
install_student_account_hardening(app, "telegram")
install_pricing_text_hardening(app)
install_tutor_archive_hardening(app)
install_telegram_subscription_booking(app)
install_telegram_tutor_confirmation(app)
install_telegram_email_hardening(app)
install_subscription_cancel_release(app)
install_telegram_completion_hardening(app)
install_telegram_materials_guard(app)
install_telegram_input_hardening(app)
install_telegram_callback_hardening(app)
install_delivery_hardening(app)
install_telegram_contact_delivery_hardening(app)
install_telegram_pagination_hardening(app)
install_telegram_hardening(app)


async def main():
    return await app.main()


if __name__ == "__main__":
    app.legacy.logging.basicConfig(level=app.legacy.logging.INFO, stream=app.legacy.sys.stdout)
    app.legacy.asyncio.run(main())
